# Generated by Django 4.0.5 on 2022-06-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mundial', '0002_remove_estadio_capacidad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Equipos',
            new_name='Equipo',
        ),
        migrations.AddField(
            model_name='estadio',
            name='capacidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
